language: go
go:
- 1.4
- 1.5
- 1.6
notifications:
  slack:
    secure: krHaZ0FmdwqFz3URuTaEHZupt2RXwkgh6m8HsWIklT3Fe9D2YlWYF0ep5HIB/ASiDFOFJf45N485IgdE2lsRE1AuhihTeLKO5BtxHC3i9DuVFBsNgCIGgL6r4Nnd6N/L7hWY8+/QfPUdj9PRmpcXj/pNgA+CYxjzSuhthsiMmSA0mHICVXe+Cn4PZ3MmqWI2ANL1RohTy88NsjCfVlp/BuLmN1c24yuG4YAwJbT6ZhaVdiLbQ3OHGvxwjvLVRDqbhYOd5DJ2UYgELC53Lky2N9Jd3I1Zejcc+9IkdSvQe4ODxtpj0ImS02CUlGQXruFOOq5riQNb/HBw2HrH69xG9L/ukH7HBABA85LVclGg2RTwu+/vNdoRjhGl1bJQmWQTwYk1eR1x0Ytk59oX4+YhMYdkeid+Y42k/0A+D0ercyiyT/UbvPWXyhAinFvICSpNIps8ga2asi8WaCtdwMB4MpueD50hD2oaCLmXbWwfag8ALi1Kgh3sc1fxMSfDAI5GBtVx/TmHlpHwOPrsAMnTXqgQh9w9aaxYP3UhPMXc/9Vq8PqncBXAc763EtA4xuA54RB4q6u4tuMYrYz9K8dcbMg23DBxM2qF7wH2Uw/OVLnkIzLsYR9pcsM4MxzT01P71YSQLoMJV7+CUB+1ICYoTYUCjh3LBT5Fnp7qPVPODjI=
